---

- name: "configure zfs on {{ ansible_distribution }}"
  include_tasks:
    file: "{{ item }}"
  vars:
    tasks_files:
      files:
        - "{{ ansible_distribution }}.yml"
  loop: "{{ q('first_found', tasks_files, errors='ignore') }}"
